<?php
namespace Example\Command;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-05 at 17:17:56.
 */
class CommandEchoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CommandEcho4chstx
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CommandEcho;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Example\Command\CommandEcho::getCommand
     * @todo   Implement testGetCommand().
     */
    public function testGetCommand()
    {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Example\Command\CommandEcho::setParam
     * @todo   Implement testSetParam().
     */
    public function testSetParam()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Example\Command\CommandEcho::compose
     * @todo   Implement testCompose().
     */
    public function testCompose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Example\Command\CommandEcho::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
