<?php
namespace Example\Command\Tests;

use AdamBrett\ShellWrapper\Command;
use Example\Command\CommandEcho;
use Logger;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-05 at 17:17:56.
 */
class CommandEchoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CommandEcho4chstx
     */
    protected $object;
    private $log;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->log = \Logger::getLogger('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Example\Command\CommandEcho::getCommand
     * @todo   Implement testGetCommand().
     */
    public function testGetCommand()
    {
        $this->log->info("testGetCommand");
        $this->object = new CommandEcho();
        $command = $this->object->getCommand();
        $this->assertInstanceOf('AdamBrett\ShellWrapper\Command', $command);
    }

    public function testToString()
    {
        $this->log->info("testToString");
        $this->object = new CommandEcho();
        $this->assertEquals('echo', (string) $this->object->getCommand());
    }

    /**
     * @covers Example\Command\CommandEcho::setParam
     * @todo   Implement testSetParam().
     */
    public function testSetParam()
    {
        $this->log->info("testSetParam");
        $this->object = new CommandEcho();
        $this->object->setParam('time');
        $this->assertEquals("echo 'time'", (string) $this->object->getCommand());
    }
}
